//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUplaodDownload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadDownload
    {
        public int fileid { get; set; }
        public Nullable<int> ticketnumber { get; set; }
        public string filename { get; set; }
        public string filetype { get; set; }
        public byte[] filedata { get; set; }
    }
}
